### ISSUE TITLE
Rsync failes consistently

### ISSUE THREAD

**Issue by AngelFreak** [Drillster/drone-rsync#18]
I have the following deploy step:
```
- name: deploy-website
  image: drillster/drone-rsync
  settings:
    hosts:
      from_secret: plugin_hosts
    port: "2223"
    key:
      from_secret: rsync_key
    user:
      from_secret: rsync_user
    source: ./dst/*
    target:
      from_secret: plugin_target
    recursive: true
    delete: true
```
But when the step is run i get the errors:
```
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3] 
```

I tried running the command printed at the first line in hand, and it all works. It's only a problem when i try to run it from drone.

I have trawled through the discourse, and github issues and tried the proposed solutions. Nothing works.
