### ISSUE TITLE
Rsync: connection unexpectedly closed

### ISSUE THREAD

**Issue by tubia** [Drillster/drone-rsync#23]
Hi,  
I am experiencing an issue similar to #18 .

This is my `.drone.yml` file:
```yml
kind: pipeline
type: docker
name: default

steps:
  - name: deploy
    image: drillster/drone-rsync
    environment:
      RSYNC_KEY:
        from_secret: ssh_key
      RSYNC_USER:
        from_secret: user
    settings:
      hosts: 
        - test.example.com
      source: ./
      target: ~/myfolder
      script:
        - touch test
```

This is the log of the `build` job:
```drone
latest: Pulling from drillster/drone-rsync
Digest: sha256:<hash>
Status: Image is up to date for drillster/drone-rsync:latest
Port not specified, using default port 22!
$ rsync -az  -e 'ssh -p 22 -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o StrictHostKeyChecking=no' ./ ******@test.example.com:~/myfolder ...
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]
```

Any idea on how to debug this?
