### ISSUE TITLE
Create ARM & ARM64 target images

### ISSUE THREAD

**Issue by cierzniak** [Drillster/drone-rsync#28]
Hi,
I've installed Drone on arm (Raspberry Pi) machine and can't use this plugin image. The log output shows
```
latest: Pulling from drillster/drone-rsync
Digest: sha256:7a784ca34d783affb8cc6d9c7f8a51066fcff4b6db50d490645fb82db23e3afd
Status: Downloaded newer image for drillster/drone-rsync:latest
standard_init_linux.go:211: exec user process caused "exec format error"
```
and fails.

Pleasecreate arm & arm64 targets images since Docerfie doesn't contain any magic supported only by amd64 platform.

**Comment by CodeDoctorDE** [comment]
👍

**Comment by gueldenstone** [comment]
I just did a multi platform build for linux/amd and linux/arm64 and uploaded it here: https://hub.docker.com/r/gueldenstone/drone-rsync

Tell me if someone needs another platform.

**Comment by cierzniak** [comment]
I used this pipeline for a while:

```yaml
---
kind: pipeline
type: docker
name: deploy
platform: { arch: arm64 }
trigger:
  event: [ promote ]
  target: [ production ]
steps:
- name: build
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    username: { from_secret: docker_username }
    password: { from_secret: docker_password }
    repo: registry.example.com/my-repo/my-image
    registry: registry.example.com
    tags: [ latest ]
    platforms: [ linux/arm64, linux/amd64 ]
```

Some time ago I changed my Raspberry Pi cluster to little Dell server so now I have arm64 architecture.

After 2 years without any activity I hope we can close this issue as "won't fix".
